### ISSUE TITLE
Add an optional variable for PvE combat logging.

### ISSUE THREAD

**Issue by dylanjkl** [ChanceSD/PvPManager#230]
I am aware that the title implicitly says PvPManager, but I believe a small feature like enabling the combat logging feature (as this is one of the best combat logging plugins I have found) on mobs and entity blocks such as lava would be a great option - it would allow for more efficient player-stalking from players that prefer to take a tactical approach - waiting for a mob to tag the player then moving in; another possible implementation could be combat tagging whenever a player comes into contact with a dangerous substance such as lava - as alot of people in my factions server will leave the game when met with overwhelming mobs or falling into lava to wait for a member to go and clear the area for them to rejoin safely.

**Comment by NoChanceSD** [comment]
This is already a feature in the premium version but I have to say that it wasn't tested a lot since afaik not a lot of people use it. From what I tested with the most common mobs it seemed to work fine though. I also have a "any damage" tag option that tags with lava damage but also tags with everything else such as fall damage so not sure if that's something you would want.
