### ISSUE TITLE
Player tab list - Customize the tab. 

### ISSUE THREAD

**Issue by demuuns** [ChanceSD/PvPManager#297]
Hello, a friend of mine uses your PvPManager plugin, and we're having trouble figuring out how to display who has PVP (and any other features) on the player tab list.

I'd like you to direct me through the commands so that we can set up a few things on our Minecraft server, thank you!

**Comment by ChanceSD** [comment]
By enabling this setting (change to true): https://github.com/ChanceSD/PvPManager/blob/811b8c77afe2bf02ead5e056e143f8c6350a3a10/PvPManager/src/main/resources/config.yml#L167

Then you can change the prefix below and it should show up in tab, If it doesn't its probably because you are using tab plugins that override the name in tab.
