### ISSUE TITLE
PvPManager blocks /toggle command

### ISSUE THREAD

**Issue by ItzRonaldMLG** [ChanceSD/PvPManager#392]
**Describe the bug**
When PvPManager is installed i cant use ''/toggle'', for example ChatControlRed: ''/toggle msg''.
It wont toggle and there are no errors or other  messages in the chat nor the console.

**To Reproduce**
1. Instal plugin with ''/toggle <feature>''
2. Use the ''/toggle <feature>'' command

**Expected behavior**
The command worked, instate it doesnt work anymore

**Plugin and Server version**
PvPManager Lite 3.12.12

**Comment by ChanceSD** [comment]
You have to configure commands allowed in combat https://github.com/ChanceSD/PvPManager/blob/544f3fd9764af5ba1d3027099466035cc2e2d012/pvpmanager/src/main/resources/config.yml#L109

**Comment by ItzRonaldMLG** [comment]
You dont need to be in combat to get this error/bug.
The command ''/toggle'' and ''/toggle <feature>'' dont work with this plugin installed for some reason.

**Comment by ChanceSD** [comment]
No idea then, there's nothing blocking commands unless in combat

**Comment by ChanceSD** [comment]
Try removing toggle from the command list and run /pmr reload

**Comment by ItzRonaldMLG** [comment]
toggle was not in the whitelist before you told me it might work in the first comment, so it didnt fix it sadly

**Comment by ChanceSD** [comment]
Might not be the issue but keep in mind it's a blacklist, since you have `Whitelist: false` so those commands will be blocked
If removing the command doesn't work, then you probably need to ask ChatControlRed, maybe they hook into PvPManager or something like that.
It's also not a command conflict since we only have `togglepvp` and `pvptoggle` as aliases for /pvp, no /toggle command
