### ISSUE TITLE
Plugin gets detected as Severe Threat and gets instantly deleted, cannot add it to an exclusion list whatsoever.

### ISSUE THREAD

**Issue by Clyde6790pGIT** [ChanceSD/PvPManager#519]
### Describe the bug
Due to the new update, Windows mistakens this plugin as a severe malware and removes it, which I am sure it is not.

### To reproduce the bug
Steps to reproduce the behavior, example:
1. Update the plugin
2. Windows defender will freak out and delete it instantly, not allowing the user to exempt it at all.

### Screenshots
If applicable, add screenshots to help explain the problem.
![image](https://github.com/user-attachments/assets/be0eaa1b-341b-4c18-a571-8f4ba9ebcf10)
![image](https://github.com/user-attachments/assets/6523bf0a-2967-436d-bd63-55730aa8a52c)

**Comment by ChanceSD** [comment]
Virustotal is showing as clean on the Microsoft check, so it shouldn't be detected by windows defender.
It used to show as detected 6 months ago but I reported it as a false positive and it has been fine since then.
So first thing try running windows update to make sure defender is update, you could also try downloading from other websites like https://github.com/ChanceSD/PvPManager/releases/tag/3.18.16 under Assets or the from the Bukkit link there.

**Comment by Clyde6790pGIT** [comment]
Ok, thank you for your assistance, hopefully Microsoft removes this from their virus database as Bitdefender is marking it as clean.

**Comment by ChanceSD** [comment]
@Clyde6790pGIT Are you able to check if it still happens? After updating windows defender it doesn't seem to detect it anymore for me.

**Comment by ChanceSD** [comment]
This should be solved, someone let me know if not.

**Comment by Clyde6790pGIT** [comment]
> This should be solved, someone let me know if not.

Solved, the defender ui allowed me to recover the file but I just downloaded a new one since it seems corrupted
