### ISSUE TITLE
The network protocol error caused the player to be kicked out.

### ISSUE THREAD

**Issue by Hiddenmn** [ChanceSD/PvPManager#521]
### Describe the bug
There is a conflict between PvPManager and tab-Bridge of Tab. When players enter pvptag, sometimes players are prompted that the network protocol is wrong and kicked out of the server. The server agent is velocity3.3.0 and the sub-server is purpur1.21.

### To reproduce the bug
1. using tab on 1.velocity
2. tab-brigde and pvpmanager are used on the sub-server.
3. the player enters pvptag
4. During the duration of pvptag, you can use btab reload on velocity, at which time all players are prompted that the network protocol is wrong and kicked out of the server. Even if you don't use btab reload, all players will be kicked out of the server when they encounter automatic tab refresh during the duration of pvptag.

### Plugin and Server version
PvPManager-3.34.9
The server agent is velocity3.3.0.
The sub-server is purpur1.21.

**Comment by ChanceSD** [comment]
Have you tried updating TAB on both sides?
Also try updating PvPManager and setting `Nametag prefix` to empty so that PvPManager doesn't use scoreboard teams.

**Comment by Hiddenmn** [comment]
I have tried the latest relese version 4.1.6 of tab and the v5 version under development. tab-brigde uses version 5.0.7, what's means updating tab on both sides? Only velocity needs to install tab, and all sub-servers use tab-brigde.

**Comment by Hiddenmn** [comment]
It is true that setting the Nametag prefix to null will not trigger again, which seems to be the cause of incompatibility with tab-brigde. Can you add a function compatible with tab-brigde?

**Comment by ChanceSD** [comment]
As far as I can tell this is an issue caused by TAB. the most I can do is automatically disable the nametags in the code when TAB is detected running. Which is basically it's what you already did by setting nametag prefix to empty.

Unless TAB-bridge has the same API as normal TAB, then I could use it to change nametags but I don't think it's possible.

**Comment by Hiddenmn** [comment]
Is it possible to separate %pvpmanager_combat_prefix% from the NameTag Prefix? I mean %pvpmanager_combat_prefix% If the tagprefix applied in the tab is actually valid, However, the current use of %pvpmanager_combat_prefix% means that the NameTag Prefix of PvPManager is not empty, which will lead to conflicts. So can you customize %pvpmanager_combat_prefix% without enabling the NameTag Prefix of PVP manager?

**Comment by ChanceSD** [comment]
I will try to make that work next update, it will disable nametags while still allowing the placeholder.

Also btw I just tested and I have the same issue as you described, seems like it only happens when using TAB-bridge, with normal TAB it works fine.
Maybe it should be reported to TAB-bridge but honestly I won't bother investigating this further, I will just not use scoreboard teams if TAB-bridge is present.
